### ISSUE TITLE
ansible 2.5.1 in Cloudshell

### ISSUE THREAD

**Issue by litvos** [Azure/azure_modules#40]
Hi,
what is an official way to install ansible 2.5.1 in the cloudshell? There is only 2.4 available and it does not include following fix:
https://github.com/ansible/ansible/pull/35038

I would be grateful as well for the information what is the cleanest way to install https://github.com/Azure/azure_preview_modules or https://github.com/Azure/azure_modules in the cloudshell.

thanks

**Comment by yuwzho** [comment]
already in v2.5
