### ISSUE TITLE
zone option is missing in azure_rm_virtualmachine

### ISSUE THREAD

**Issue by apendragon** [Azure/azure_modules#42]
Hello,

It would be very usefull to add a "zone" option in azure_rm_virtualmachine to set an [availability zone](https://docs.microsoft.com/en-us/azure/availability-zones/az-overview) while creating a VM.
Is it already planned in the roadmap ?

Thx

**Comment by yuwzho** [comment]
@apendragon  Maybe you can create an issue to Ansible/ansible repo, this repo is to sync the pre released bit from ansible repo.
